### PR TITLE
Revert enabling "warnings as errors" in the default build

### PR DESCRIPTION
**Pull request by oprypin**
* Following up and reverting part of https://github.com/SFML/imgui-sfml/pull/246

### CODE REVIEW

**Comment by ChrisThrasher** [comment]
This is overkill. Remove `-Werror` if you're worried about that. Better yet add a new option like SFML does that lets users disable warnings as errors. It's a very bad idea to entirely remove compiler warnings because it's increasing the chances of bugs or other code smells getting in.

**Comment by ChrisThrasher** [comment]
https://github.com/SFML/imgui-sfml/commit/7da7dfe10ee27c48878195940a5355eed60e3104

Here's the fix you actually want. Our list of warnings is only going to grow so it's good to have this option for those who for whatever reason are seeing a warning that isn't already caught in CI.

**Comment by oprypin** [comment]
I want to make that release happen, and take no risks in it.

**Comment by ChrisThrasher** [comment]
See https://github.com/SFML/imgui-sfml/pull/251

**Pull request merged**
